/**
 * src/hooks.server.ts
 * SvelteKit Server Hooks
 *
 * Applies security headers and middleware to all server responses.
 * This provides defense-in-depth alongside Firebase Hosting headers.
 *
 * NOTE: With adapter-static these hooks only run in the dev server (and at
 * prerender time) — they are NOT active on a deployed static site. Production
 * headers come from firebase.json; the production CSP is generated by
 * SvelteKit from `kit.csp` in svelte.config.js. Keep those in sync with
 * $lib/config/security.ts. If you switch to a server adapter (adapter-node,
 * etc.), these hooks become your production headers.
 */

import type { Handle } from '@sveltejs/kit';
import { getSecurityConfig, generateCSPHeader } from '$lib/config/security';
import { sequence } from '@sveltejs/kit/hooks';

/**
 * Security headers hook
 * Applies comprehensive security headers to all responses
 */
const securityHeaders: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);

  const securityConfig = getSecurityConfig();

  // Apply security headers
  const headers = new Headers(response.headers);

  // Basic security headers
  headers.set('X-Frame-Options', securityConfig.headers['X-Frame-Options']);
  headers.set('X-Content-Type-Options', securityConfig.headers['X-Content-Type-Options']);
  headers.set('X-XSS-Protection', securityConfig.headers['X-XSS-Protection']);
  headers.set('Referrer-Policy', securityConfig.headers['Referrer-Policy']);
  headers.set('Permissions-Policy', securityConfig.headers['Permissions-Policy']);

  // HSTS only in production and over HTTPS
  if (import.meta.env.PROD && event.url.protocol === 'https:') {
    headers.set('Strict-Transport-Security', securityConfig.headers['Strict-Transport-Security']);
  }

  // Content Security Policy
  const cspHeader = generateCSPHeader(securityConfig.csp);
  headers.set('Content-Security-Policy', cspHeader);

  // Additional security headers
  // (COEP: require-corp is deliberately NOT set — it blocks every cross-origin
  // subresource that lacks a CORP header, which breaks Google Fonts, avatars,
  // reCAPTCHA, etc. Enable it only if you need cross-origin isolation.)
  headers.set('X-Permitted-Cross-Domain-Policies', 'none');
  headers.set('Cross-Origin-Opener-Policy', 'same-origin');
  headers.set('Cross-Origin-Resource-Policy', 'same-origin');

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers
  });
};

/**
 * Request validation hook
 * Validates incoming requests for security issues
 */
const requestValidation: Handle = async ({ event, resolve }) => {
  const { request } = event;

  // Validate Content-Type for state-changing methods
  if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method)) {
    const contentType = request.headers.get('content-type');

    // Allow FormData, JSON, or no body
    if (contentType &&
        !contentType.includes('application/json') &&
        !contentType.includes('multipart/form-data') &&
        !contentType.includes('application/x-www-form-urlencoded')) {
      return new Response('Invalid Content-Type', { status: 415 });
    }
  }

  // Check for suspicious patterns in URL
  const url = event.url.pathname;
  if (url.includes('../') || url.includes('..\\') || url.includes('%2e%2e')) {
    return new Response('Invalid URL', { status: 400 });
  }

  return resolve(event);
};

/**
 * CORS configuration hook
 * Configurable CORS handling for API routes
 */
const corsHeaders: Handle = async ({ event, resolve }) => {
  // Only apply CORS to API routes
  if (event.url.pathname.startsWith('/api')) {
    const allowedOrigin = getAllowedOrigin(event.request.headers.get('origin'));

    // Handle preflight requests
    if (event.request.method === 'OPTIONS') {
      const headers: Record<string, string> = {
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-CSRF-Token',
        'Access-Control-Max-Age': '86400',
      };
      if (allowedOrigin) {
        headers['Access-Control-Allow-Origin'] = allowedOrigin;
        headers['Access-Control-Allow-Credentials'] = 'true';
        headers['Vary'] = 'Origin';
      }
      return new Response(null, { headers });
    }

    const response = await resolve(event);

    // Add CORS headers to API responses — only for allowlisted origins.
    // Disallowed origins get no CORS headers at all (the browser then blocks
    // the cross-origin read); never reflect the origin or emit the literal
    // string 'null', which would match sandboxed-iframe/file:// origins.
    if (allowedOrigin) {
      const headers = new Headers(response.headers);
      headers.set('Access-Control-Allow-Origin', allowedOrigin);
      headers.set('Access-Control-Allow-Credentials', 'true');
      headers.append('Vary', 'Origin');

      return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers
      });
    }

    return response;
  }

  return resolve(event);
};

/**
 * Get allowed origin for CORS
 * Returns the origin if it's in the allowlist, otherwise null (no CORS headers)
 */
function getAllowedOrigin(origin: string | null): string | null {
  if (!origin) return null;

  const allowedOrigins = [
    'http://localhost:5173',
    'http://localhost:4173',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:4173',
  ];

  // Add production domain from environment
  const appDomain = import.meta.env.VITE_APP_DOMAIN;
  if (appDomain && appDomain !== 'localhost') {
    allowedOrigins.push(`https://${appDomain}`);
    allowedOrigins.push(`https://www.${appDomain}`);
  }

  return allowedOrigins.includes(origin) ? origin : null;
}

/**
 * Combine all hooks in sequence
 * Order matters: validation -> CORS -> security headers
 *
 * Rate limiting: there is intentionally no rate-limiting hook here. Anything
 * running in this process (or worse, fabricated X-RateLimit-* headers) is not
 * a security control — enforce rate limits server-side in your API backend
 * (Firebase Cloud Functions, API gateway, etc.).
 */
export const handle = sequence(
  requestValidation,
  corsHeaders,
  securityHeaders
);
